#zentrale Konfigurationsdatei für die Spring Boot Anwendung
spring.application.name=spring_thymeleaf
# man kann theroretisch den Port ändern mit server.port=9090



#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/landverwaltung
#spring.datasource.username=root
#spring.datasource.password=